### ISSUE TITLE
Are bookmarklets working?

### ISSUE THREAD

**Issue by ghost** [luckycdev/bookmarklets#1]
The other day when I clicked my bookmarklet it didn't work. Gogardian is installed so is there a way that my school can block them?

**Comment by luckycdev** [comment]
> The other day when I clicked my bookmarklet it didn't work. Gogardian is installed so is there a way that my school can block them?

yes your school can block them, with the latest Chromebook update they also stopped working for me, I'm not sure what to do as it's not blocked in my Google policies I've been trying to find a fix 

EDIT: yeah they are disabled on new chrome versions im pretty sure.
